version: '3.8'

services:
  app:
    image: openjdk:11-jre-slim
    container_name: demo-with-tests
    ports:
      - "8087:8087"
    volumes:
      - ./target/demo-with-tests.jar:/target/demo-with-tests.jar
    depends_on:
      - postgres
      - flyway
    command: java -jar /target/demo-with-tests.jar
    # Service health check
    healthcheck:
      test: curl -f http://localhost:8087/profile || exit 1
      interval: 1m
      timeout: 10s
      retries: 2

  flyway:
    image: boxfuse/flyway:latest-alpine
    command: -url=jdbc:postgresql://postgres:5432/employee -schemas=public -user=postgres -password=admin migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2

volumes:
  postgres-data:
